inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Metrics/ParameterLists:
  Enabled: true
  Max: 5
  CountKeywordArgs: true

Rails/TimeZone:
  Enabled: true
  EnforcedStyle: strict

Rails/Date:
  Enabled: true
  EnforcedStyle: strict

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
